services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles:
      - production

  db-dev:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: .env.dev
    ports:
      - 5432:5432
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    profiles:
      - development

  backend:
    build: backend
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - 3000:3000
    depends_on:
      - db
    profiles:
      - production

  backend-dev:
    build:
      context: backend
      dockerfile: Dockerfile.debug
    env_file: .env.dev
    environment:
      - DB_HOST=db-dev
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db-dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    profiles:
      - development
  
  frontend:
    build: frontend
    ports:
      - 80:80
    profiles:
      - production

volumes:
  db-data:
  db-data-dev:
