services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
